Repository leopachecof/bibliotech, pull requests merged in 2023-04, with the labels that each got.

#22 Realizado alterações na task #38
  package-lock.json
  package.json
  src/pages/DetalhesLivro/DetalhesLivro.jsx
  src/pages/Livros/Livros.jsx
Labels: documentation, enhancement

#23 Task4
  src/pages/Home/Home.css
  src/pages/Home/Home.jsx
Labels: documentation

#27 adição data entrega emprestimos
  src/pages/AdicionarEmprestimo/AdicionarEmprestimo.jsx
  src/pages/EditarEmprestimo/EditarEmprestimo.jsx
  src/pages/Emprestimos/Emprestimos.jsx
Labels: documentation

#29 melhorias acessibilidade - task #8
  src/components/Menu/Menu.jsx
  src/pages/Cadastro/Cadastro.jsx
  src/pages/Emprestimos/Emprestimos.jsx
  src/pages/Livros/Livros.jsx
  src/pages/Login/Login.jsx
Labels: documentation

#31 Task31
  src/assets/icons/mapa-da-empatia-1.png
  src/components/Menu/Menu.jsx
  src/firebase/config.js
  src/firebase/emprestimos.js
  src/pages/Emprestimos/Emprestimos.jsx
  src/pages/Home/Home.jsx
Labels: documentation

#32 Customização do Bootstrap com uso do Sass
  .vscode/settings.json
  src/App.jsx
  src/index.css
  src/index.css.map
  src/index.jsx
  src/index.scss
  src/pages/Livros/Livros.jsx
Labels: enhancement

#33 task 17 completa
  src/assets/icons/facebookIcon.png
  src/assets/icons/githubicon.png
  src/firebase/auth.js
  src/pages/Cadastro/Cadastro.jsx
  src/pages/Login/Login.jsx
Labels: documentation

#36 criação da funcionalidade de soft delete
  src/firebase/livros.js
  src/index.scss
  src/pages/AdicionarLivro/AdicionarLivro.jsx
  src/pages/Livros/Livros.jsx
Labels: enhancement

#37 ajustes
  src/index.scss
  src/pages/Home/Home.css
Labels: bug

#39 implementaçao de Footer e ocultar/mostrar senha
  src/components/Footer/Footer.css
  src/components/Footer/Footer.jsx
  src/pages/Cadastro/Cadastro.jsx
  src/pages/Login/Login.jsx
Labels: documentation

#40 tasks realizadas
  src/App.jsx
  src/components/Menu/Menu.jsx
  src/pages/EsqueciSenha/EsqueciSenha.jsx
  src/pages/NotFound/NotFound.css
  src/pages/NotFound/NotFound.jsx
  src/pages/VendaLivro/VendaLivro.css
  src/pages/VendaLivro/VendaLivro.jsx
Labels: documentation

#41 task20
  src/App.jsx
  src/components/Menu/Menu.jsx
  src/firebase/autores.js
  src/pages/AdicionarLivro/AdicionarLivro.jsx
  src/pages/EditarLivro/EditarLivro.jsx
  src/pages/Livros/Livros.jsx
Labels: documentation

#43 task 73 completa
  src/App.jsx
  src/assets/icons/facebookIcon.png
  src/assets/icons/google-colorido.svg
  src/assets/icons/google-white.svg
  src/assets/icons/googleIcon.png
  src/firebase/livros.js
  src/index.scss
  src/pages/Cadastro/Cadastro.jsx
  src/pages/Emprestimos/Emprestimos.jsx
  src/pages/EsqueciSenha/EsqueciSenha.jsx
  src/pages/Login/Login.jsx
Labels: documentation

#45 arrumando interface
  src/pages/Cadastro/Cadastro.jsx
  src/pages/Login/Login.jsx
Labels: bug

#46 Criação da task 13 Área de Perfil do Usuário
  src/App.jsx
  src/firebase/auth.js
  src/index.scss
  src/pages/PerfilUsuario/PerfilUsuario.jsx
Labels: documentation

#47 Realização da task multiplas categorias de livros
  src/pages/AdicionarLivro/AdicionarLivro.jsx
  src/pages/EditarLivro/EditarLivro.jsx
Labels: documentation

#48 correção codigo
  src/pages/AdicionarEmprestimo/AdicionarEmprestimo.jsx
  src/pages/Emprestimos/Emprestimos.jsx
Labels: bug

#49 Ajuste de bug
  src/pages/DetalhesLivro/DetalhesLivro.jsx
Labels: bug
